version: '3'

services:
  master:
    image: itzg/elasticsearch
    environment:
      TYPE: MASTER
      UNICAST_HOSTS: master
      MIN_MASTERS: 1
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
  data:
    image: itzg/elasticsearch
    environment:
      TYPE: DATA
      UNICAST_HOSTS: master
      DISCOVER_TRANSPORT_IP: eth0
      DISCOVER_HTTP_IP: eth0
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 60s
  gateway:
    image: itzg/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      TYPE: GATEWAY
      UNICAST_HOSTS: master
  ingest:
    image: itzg/elasticsearch
    environment:
      TYPE: INGEST
      UNICAST_HOSTS: master
  kibana:
    image: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://gateway:9200
  indexer:
    image: "redteamobile/logstash:5.2.2-indexer"
    environment:
      - "KAFKA_BOOTSTRAP_SERVERS=172.31.28.28:9092,172.31.16.213:9092,172.31.17.24:9092"
    depends_on:
      - ingest
