version: "3"
services:
  shipper:
    image: "redteamobile/logstash:5.2.2-shipper"
    environment:
      - "KAFKA_BOOTSTRAP_SERVERS=172.31.28.28:9092,172.31.16.213:9092,172.31.17.24:9092"
      - "S3_ACCESS_KEY_ID="
      - "S3_SECRET_ACCESS_KEY="
      - "S3_REGION="
      - "S3_BUCKET="
    ports:
      - "11101:12201/udp"
    deploy:
      mode: replicated
      replicas: 3
