version: "3"
services:
  shipper:
    image: "redteamobile/logstash:5.2.2-shipper"
    environment:
      - "KAFKA_BOOTSTRAP_SERVERS="
      - "S3_ACCESS_KEY_ID="
      - "S3_SECRET_ACCESS_KEY="
      - "S3_REGION="
      - "S3_BUCKET="
    ports:
      - "11101:12201/udp"
    deploy:
      mode: replicated
      replicas: 3
